const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const H={"apikey":SUPABASE_KEY,"Authorization":"Bearer "+SUPABASE_KEY,"Content-Type":"application/json","Prefer":"return=representation"};
let admin=false, activeRoom=null, currentProfile=null;
async function api(path,opt={}){let r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:H,...opt});if(!r.ok)throw Error(await r.text());return await r.json()}
async function upload(bucket,file){if(!file)return null;let name=`${Date.now()}-${file.name}`.replace(/\s+/g,"-");let r=await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}/${name}`,{method:"POST",headers:{"apikey":SUPABASE_KEY,"Authorization":"Bearer "+SUPABASE_KEY,"x-upsert":"true","content-type":file.type||"application/octet-stream"},body:file});if(!r.ok){alert("Upload failed. Check Supabase bucket is public + policies allow upload.");throw Error(await r.text())}return `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${name}`}
function show(x){x.classList.remove("hidden")}function hide(x){x.classList.add("hidden")}
createTab.onclick=()=>{show(createForm);hide(signinForm);createTab.classList.add("active");signinTab.classList.remove("active")};signinTab.onclick=()=>{show(signinForm);hide(createForm);signinTab.classList.add("active");createTab.classList.remove("active")};
function media(url,type=""){if(!url)return "";let l=url.toLowerCase();if(type.includes("video")||l.match(/mp4|mov|webm/))return `<div class="media"><video src="${url}" controls playsinline></video></div>`;if(type.includes("image")||l.match(/jpg|jpeg|png|gif|webp/))return `<div class="media"><img src="${url}"></div>`;return `<a class="file-name" href="${url}" target="_blank">Open file</a>`}
async function createProfile(){if(!firstName.value||!surname.value||!contact.value||!province.value||!age.value||!industry.value)return alert("Please complete all fields.");if(!consent.checked)return alert("Please accept the consent form.");let body={full_name:firstName.value,surname:surname.value,contact:contact.value.toLowerCase(),province:province.value,age_range:age.value,industry:industry.value,thought:"Can’t wait for Opportunities.",role:"admin"};let existing=await api(`profiles?contact=eq.${encodeURIComponent(body.contact)}&select=*`);let p=existing.length?(await api(`profiles?contact=eq.${encodeURIComponent(body.contact)}`,{method:"PATCH",body:JSON.stringify(body)}))[0]:(await api("profiles",{method:"POST",body:JSON.stringify(body)}))[0];localStorage.setItem("forwardContact",p.contact);enter(p,true)}
async function signIn(){let c=signinContact.value.toLowerCase().trim();let r=await api(`profiles?contact=eq.${encodeURIComponent(c)}&select=*`);if(!r.length)return alert("No Forward profile found.");localStorage.setItem("forwardContact",c);enter(r[0],true)}
joinBtn.onclick=()=>createProfile().catch(e=>alert(e.message));signinBtn.onclick=()=>signIn().catch(e=>alert(e.message));signOut.onclick=()=>{localStorage.removeItem("forwardContact");location.reload()}
function setProfile(p){currentProfile=p;profileName.textContent=`${p.full_name||""} ${p.surname||""}`;pProvince.textContent=p.province||"-";pIndustry.textContent=p.industry||"-";pAge.textContent=p.age_range||"-";pRole.textContent=p.role||"member";avatar.textContent=(p.full_name||"F")[0].toUpperCase();status.textContent=`${p.province||"Access"} • ${p.industry||"Member"}`;thoughtDisplay.textContent=`“${p.thought||"Can’t wait for Opportunities."}”`;admin=(p.role==="admin" || localStorage.getItem("forwardFounderMode")==="true"); adminToggle.textContent=admin?"Admin On":"Admin"}
function enter(p,delay=true){hide(auth);if(delay)show(loading);setTimeout(async()=>{hide(loading);show(app);setProfile(p);await loadAll()},delay?5000:0)}
(async()=>{let c=localStorage.getItem("forwardContact");if(c){let r=await api(`profiles?contact=eq.${encodeURIComponent(c)}&select=*`).catch(()=>[]);if(r.length)enter(r[0],false)}})();
async function seed(){if(!(await api("rooms?select=id&limit=1")).length)await api("rooms",{method:"POST",body:JSON.stringify(["Announcements|Admin-only updates|Read-only","General Access|Open ecosystem room|Open","SMMEs|Entrepreneurs and business owners|Open","Farmers|Agriculture and farming access|Open","Funding & Grants|Capital and opportunity access|Open","E-commerce|Online selling and digital commerce|Open","Green Sector|Energy, climate and sustainability|Open","Technology|Builders and digital work|Open","Media|Creative economy and visibility|Open","NGOs & NPOs|Impact and partnerships|Open","Learnerships|Skills opportunities|Open","People Living With Disabilities|Inclusive access|Open","Unemployed Youth|Youth opportunity access|Open","Unemployed General|Open opportunity access|Open","Essentials|Essentials membership room|Closed","Breakthrough|Breakthrough membership room|Closed","Premium Experience|Premium private room|Closed"].map(x=>{let a=x.split("|");return{name:a[0],description:a[1],status:a[2],members:0}}))});if(!(await api("posts?select=id&limit=1")).length)await api("posts",{method:"POST",body:JSON.stringify([{title:"Welcome To Access.",body:"Forward connects people, opportunities, rooms and movement.",likes:12},{title:"The Future Of South African Wealth Is Human Capital.",body:"South Africa does not lack talent. It lacks access, alignment and proximity to opportunity.",likes:21}])});if(!(await api("stories?select=id&limit=1")).length)await api("stories",{method:"POST",body:JSON.stringify(["Forward","FNB","Spar","Partners","Rooms","Advertising"].map(label=>({label})))});}
async function loadAll(){await seed();await Promise.all([loadStories(),loadPosts(),loadRooms(),loadReels(),loadEvents(),loadMarket()]);renderSocials();applyAdmin();status.textContent="Live"}
function page(id){$$(".page").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");$$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===id))}$$(".nav").forEach(n=>n.onclick=()=>page(n.dataset.page));adminToggle.onclick=()=>{admin=!admin;localStorage.setItem("forwardFounderMode", admin?"true":"false");applyAdmin();adminToggle.textContent=admin?"Admin On":"Admin";loadPosts&&loadPosts();loadEvents&&loadEvents();loadMarket&&loadMarket();loadReels&&loadReels();};function applyAdmin(){$$(".admin-only").forEach(e=>e.classList.toggle("hidden",!admin)); const ra=document.getElementById("roomAdmin"); if(ra)ra.classList.toggle("hidden",!admin);}
async function loadStories(){
  let r=[];
  try{r=await api("stories?select=*&order=created_at.asc")}catch(e){r=[]}
  if(!r.length){
    r=[{label:"Forward"},{label:"FNB"},{label:"Spar"},{label:"Partners"},{label:"Rooms"},{label:"Advertising"}];
  }
  stories.innerHTML=r.map((s,i)=>`<div class="story ${i==0?"active":""}" data-label="${s.label}" data-url="${s.media_url||""}"><div class="ring" ${s.media_url?`style="background-image:url('${s.media_url}')"`:""}>${s.media_url?"":s.label[0]}</div><small>${s.label}</small></div>`).join("");
  $$(".story").forEach(st=>st.onclick=()=>{
    show(storyViewer);
    storyContent.innerHTML=st.dataset.url?(st.dataset.url.match(/mp4|mov|webm/)?`<video src="${st.dataset.url}" controls autoplay playsinline></video>`:`<img src="${st.dataset.url}">`):`<div class="fallback">${st.dataset.label}</div>`;
  });
}
closeStory.onclick=()=>hide(storyViewer);
addStoryBtn.onclick=async()=>{
  let label=prompt("Story label","New Story"); if(!label)return;
  let input=document.createElement("input"); input.type="file"; input.accept="image/*,video/*";
  input.onchange=async()=>{
    let url=null;
    try{url=await upload("stories",input.files[0]); await api("stories",{method:"POST",body:JSON.stringify({label,media_url:url})});}
    catch(e){alert("Story upload failed: "+e.message)}
    loadStories();
  };
  input.click();
};
quickStory.onclick=()=>addStoryBtn.click();
async function loadPosts(){let r=await api("posts?select=*&order=created_at.desc");feed.innerHTML=r.map(p=>`<article class="feed-card"><div class="feed-head"><span>Forward</span><small>Update</small></div><h3>${p.title}</h3><p>${p.body||""}</p>${media(p.media_url,p.media_type||"")}<div class="actions"><button class="like" data-likes="${p.likes||0}">♡ <span>${p.likes||0}</span></button><button>Comment</button><button>Share</button><button>React</button></div>${admin?`<div class="admin-panel"><button onclick="del('posts','${p.id}',loadPosts)">Delete</button></div>`:""}</article>`).join("");$$(".like").forEach(b=>b.onclick=()=>{let liked=b.classList.toggle("liked");let n=Number(b.dataset.likes)+(liked?1:0);b.innerHTML=`${liked?"♥":"♡"} <span>${n}</span>`})}
createPost.onclick=async()=>{let f=postFile.files[0],url=f?await upload("feed-media",f):null;await api("posts",{method:"POST",body:JSON.stringify({title:postTitle.value||"Forward Update",body:postBody.value||"",media_url:url,media_type:f?f.type:null,likes:0})});postTitle.value=postBody.value=postFile.value="";loadPosts()}
async function loadRooms(){let r=await api("rooms?select=*&order=created_at.asc");roomList.innerHTML=r.map(x=>`<button class="room-card" data-id="${x.id}"><div><h3>${x.name}</h3><p>${x.description||""}</p></div><div class="room-meta"><span class="status ${x.status!="Open"?"closed":""}">${x.status}</span><span class="count">${x.members||0} Members</span></div></button>`).join("");$$(".room-card").forEach(c=>c.onclick=()=>openRoom(c.dataset.id))}
showRoomCreate.onclick=()=>roomCreate.classList.toggle("hidden");createRoom.onclick=async()=>{await api("rooms",{method:"POST",body:JSON.stringify({name:roomNameInput.value||"New Room",description:roomDescInput.value||"Access room",status:"Open",members:0})});roomNameInput.value=roomDescInput.value="";loadRooms()}
async function openRoom(id){activeRoom=(await api(`rooms?id=eq.${id}&select=*`))[0];roomTitle.textContent=activeRoom.name;roomMeta.textContent=`${activeRoom.status} room • ${activeRoom.members||0} members • reactions enabled`;editRoomName.value=activeRoom.name;editRoomDesc.value=activeRoom.description||"";composer.classList.toggle("hidden",activeRoom.status!="Open"&&!admin);page("roomView");await loadMessages();applyAdmin()}backRooms.onclick=()=>page("rooms");saveRoom.onclick=async()=>{await api(`rooms?id=eq.${activeRoom.id}`,{method:"PATCH",body:JSON.stringify({name:editRoomName.value,description:editRoomDesc.value})});openRoom(activeRoom.id);loadRooms()};lockRoom.onclick=async()=>{await api(`rooms?id=eq.${activeRoom.id}`,{method:"PATCH",body:JSON.stringify({status:activeRoom.status=="Closed"?"Open":"Closed"})});openRoom(activeRoom.id);loadRooms()};readOnlyRoom.onclick=async()=>{await api(`rooms?id=eq.${activeRoom.id}`,{method:"PATCH",body:JSON.stringify({status:activeRoom.status=="Read-only"?"Open":"Read-only"})});openRoom(activeRoom.id);loadRooms()};deleteRoom.onclick=async()=>{await del("rooms",activeRoom.id,loadRooms);page("rooms")}
function reacts(){return `<div class="reactions">${["❤️","👍","😊","✅","💯"].map(x=>`<button>${x}</button>`).join("")}</div>`}function attachReacts(){$$(".reactions button").forEach(b=>b.onclick=()=>b.classList.toggle("active"))}async function loadMessages(){let r=await api(`messages?room_id=eq.${activeRoom.id}&select=*&order=created_at.asc`);messages.innerHTML=(r.length?r:[{author:"Forward",body:"Welcome To Forward Access."}]).map(m=>`<div class="msg"><small>${m.author||"Member"}</small>${m.body||""}${media(m.media_url,m.media_type||"")}${reacts()}</div>`).join("");attachReacts()}sendMessage.onclick=async()=>{if(!messageInput.value.trim())return;await api("messages",{method:"POST",body:JSON.stringify({room_id:activeRoom.id,author:currentProfile.full_name||"Member",body:messageInput.value})});messageInput.value="";loadMessages()};roomSendFile.onclick=async()=>{let f=roomFile.files[0];if(!f)return alert("Choose a file first.");let url=await upload("room-media",f);await api("messages",{method:"POST",body:JSON.stringify({room_id:activeRoom.id,author:"Admin",media_url:url,media_type:f.type})});roomFile.value="";loadMessages()}
showReelCreate.onclick=()=>reelCreate.classList.toggle("hidden");
async function loadReels(){
  let r=[];
  try{r=await api("reels?select=*&order=created_at.desc")}catch(e){r=[]}
  if(!r.length){
    r=[
      {title:"Inside Forward",caption:"Rooms. Access. Movement.",media_url:""},
      {title:"Opportunity Watch",caption:"Funding. Partners. Visibility.",media_url:""}
    ];
  }
  reelStack.innerHTML=r.map(x=>`<div class="reel">${x.media_url?media(x.media_url,"video"):""}<div><h2>${x.title}</h2><p>${x.caption||""}</p><div>❤️ 👍 😊 ✅ 💯</div>${admin&&x.id?`<button class="read-more" onclick="del('reels','${x.id}',loadReels)">Delete</button>`:""}</div></div>`).join("");
}
createReel.onclick=async()=>{
  let f=reelFile.files[0];
  if(!f)return alert("Choose video/image first.");
  try{
    let url=await upload("reels",f);
    await api("reels",{method:"POST",body:JSON.stringify({title:reelTitle.value||"New Reel",caption:reelCaption.value||"",media_url:url})});
    reelTitle.value=reelCaption.value=reelFile.value="";
    loadReels();
  }catch(e){alert("Reel upload failed: "+e.message)}
}
showEventCreate.onclick=()=>eventCreate.classList.toggle("hidden");async function loadEvents(){let r=await api("events?select=*&order=created_at.desc");eventsList.innerHTML=r.map(e=>`<div class="event-card"><div class="event-poster" ${e.poster_url?`style="background-image:url('${e.poster_url}')"`:""}>${e.poster_url?"":e.title}</div><h3>${e.title}</h3><p>${e.event_date||"Coming soon"} • ${e.price||"Free"}</p><button class="read-more" data-id="${e.id}">See More Details</button><div class="details" id="event${e.id}"><p>${e.details||""}</p><button>Register Interest</button>${admin?`<div class="admin-panel"><button onclick="del('events','${e.id}',loadEvents)">Delete Event</button></div>`:""}</div></div>`).join("");$$("[data-id].read-more").forEach(b=>b.onclick=()=>$("#event"+b.dataset.id).classList.toggle("open"))}createEvent.onclick=async()=>{let f=eventPoster.files[0],url=f?await upload("events",f):null;await api("events",{method:"POST",body:JSON.stringify({title:eventTitleInput.value||"New Event",event_date:eventDateInput.value||"Coming Soon",price:eventPriceInput.value||"Free",details:eventDescInput.value||"",poster_url:url})});eventTitleInput.value=eventDateInput.value=eventPriceInput.value=eventDescInput.value=eventPoster.value="";loadEvents()}
showOfferCreate.onclick=()=>offerCreate.classList.toggle("hidden");async function loadMarket(){let r=await api("marketplace?select=*&order=created_at.desc");marketList.innerHTML=r.map(o=>`<div class="market-card"><div class="product-image" ${o.image_url?`style="background-image:url('${o.image_url}')"`:""}>${o.image_url?"":o.title}</div><h3>${o.title}</h3><p>${o.price||""}</p><button>${o.button_label||"Apply"}</button><button class="read-more" data-o="${o.id}">Read More</button><div class="details" id="offer${o.id}"><p>${o.details||""}</p>${admin?`<div class="admin-panel"><button onclick="del('marketplace','${o.id}',loadMarket)">Delete Offer</button></div>`:""}</div></div>`).join("");$$("[data-o].read-more").forEach(b=>b.onclick=()=>$("#offer"+b.dataset.o).classList.toggle("open"))}createOffer.onclick=async()=>{let f=offerImage.files[0],url=f?await upload("marketplace",f):null;await api("marketplace",{method:"POST",body:JSON.stringify({title:offerTitleInput.value||"New Offer",price:offerPriceInput.value||"Custom",button_label:offerButtonInput.value,details:offerDescInput.value||"",image_url:url})});offerTitleInput.value=offerPriceInput.value=offerDescInput.value=offerImage.value="";loadMarket()}
saveThought.onclick=async()=>{if(!thoughtInput.value.trim())return;await api(`profiles?contact=eq.${encodeURIComponent(currentProfile.contact)}`,{method:"PATCH",body:JSON.stringify({thought:thoughtInput.value})});currentProfile.thought=thoughtInput.value;setProfile(currentProfile);thoughtInput.value=""};askAI.onclick=()=>{let q=aiQuestion.value.toLowerCase();let a="Forward connects people and businesses to rooms, opportunities, visibility, funding, partnerships, events and economic movement.";if(q.includes("room"))a="Rooms are private access spaces. Some are open, closed or read-only. Even closed rooms allow reactions.";else if(q.includes("market"))a="Marketplace shows memberships, tickets, partner offers, courses, sponsored products and opportunities.";else if(q.includes("event"))a="Events are Forward access rooms in real life: summits, gatherings, partner sessions and opportunity rooms.";else if(q.includes("earn"))a="Forward Earnings is coming soon for referrals, campaigns, opportunity sharing and partner activity.";aiAnswer.textContent=a}
function renderSocials(){} $$("[data-admin-go]").forEach(b=>b.onclick=()=>page(b.dataset.adminGo));assignAdmin.onclick=()=>assignRole("admin");assignPartner.onclick=()=>assignRole("partner");async function assignRole(role){let c=roleContact.value.toLowerCase().trim();if(!c)return alert("Enter member email/phone.");await api(`profiles?contact=eq.${encodeURIComponent(c)}`,{method:"PATCH",body:JSON.stringify({role})});alert(`${role} assigned if member exists.`)}async function del(table,id,cb){await api(`${table}?id=eq.${id}`,{method:"DELETE"});cb()}
