const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let admin=false, activeRoom=1, pendingPostFile=null, pendingEventFile=null, pendingOfferFile=null;
let stories=["Forward","FNB","Spar","Partners","Rooms","Advertising"];
let posts=[{title:"Welcome To Access.",type:"Opportunity Update",body:"Forward connects people, opportunities, rooms and movement.",likes:12,liked:false},{title:"The Future Of South African Wealth Is Human Capital.",type:"Access Note",body:"South Africa does not lack talent. It lacks access, alignment and proximity to opportunity.",likes:21,liked:false}];
let rooms=[["Announcements","Admin-only updates",221,true,true],["General Access","Open ecosystem room",221,false,false],["SMMEs","Entrepreneurs and business owners",84,false,false],["Farmers","Agriculture and farming access",31,false,false],["Funding & Grants","Capital and opportunity access",117,false,false],["E-commerce","Online selling and digital commerce",76,false,false],["Green Sector","Energy, climate and sustainability",62,false,false],["Technology","Builders, tools and digital work",91,false,false],["Media","Creative economy and visibility",57,false,false],["NGOs & NPOs","Impact, funding and partnerships",51,false,false],["Learnerships","Skills and learning opportunities",189,false,false],["People Living With Disabilities","Inclusive access and opportunity",19,false,false],["Unemployed Youth","Youth opportunity access",144,false,false],["Unemployed General","Open opportunity access",63,false,false],["Essentials","Essentials membership room",28,true,false],["Breakthrough","Breakthrough membership room",14,true,false],["Premium Experience","Premium private room",7,true,false]].map(r=>({name:r[0],desc:r[1],members:r[2],locked:r[3],readOnly:r[4]}));
let offers=[{title:"Essentials Membership",price:"R199 / month",button:"Apply",details:"Core access, rooms, updates and member movement."},{title:"Breakthrough Membership",price:"R499 / month",button:"Join",details:"Private rooms, stronger support, focused access and partner opportunities."},{title:"Premium Experience",price:"R699 / month",button:"Reserve",details:"Priority access, premium rooms, curated opportunities and visibility."}];
let events=[{title:"Forward Access Evening",date:"Coming Soon",price:"Invite-only",poster:"Access Evening",details:"A private gathering for founders, professionals, funders and builders."},{title:"Opportunity Room: Funding & Grants",date:"June 2026",price:"Free / RSVP",poster:"Funding Room",details:"A focused access session for funding pathways, grants and capital readiness."}];
let reels=[{title:"Inside Forward",caption:"Rooms. Access. Movement."},{title:"Opportunity Watch",caption:"Funding. Partners. Visibility."}];
let socials={website:"",instagram:"",facebook:"",linkedin:"",youtube:""};

function save(){localStorage.setItem("forwardDataV27",JSON.stringify({stories,posts,rooms,offers,events,reels,socials}));}
function load(){try{let d=JSON.parse(localStorage.getItem("forwardDataV27")||"null");if(d){stories=d.stories||stories;posts=d.posts||posts;rooms=d.rooms||rooms;offers=d.offers||offers;events=d.events||events;reels=d.reels||reels;socials=d.socials||socials;}}catch(e){}}
function fileURL(file){return new Promise((res,rej)=>{if(!file)return res(null);let r=new FileReader();r.onload=()=>res({name:file.name,type:file.type,url:r.result});r.onerror=rej;r.readAsDataURL(file);});}
function showCreate(){createForm.classList.remove("hidden");signinForm.classList.add("hidden");createTab.classList.add("active");signinTab.classList.remove("active");}
function showSignin(){signinForm.classList.remove("hidden");createForm.classList.add("hidden");signinTab.classList.add("active");createTab.classList.remove("active");}
createTab.onclick=showCreate; signinTab.onclick=showSignin;
function profiles(){try{return JSON.parse(localStorage.getItem("forwardProfilesV27")||"{}")}catch(e){return {}}}
function saveProfile(p){let ps=profiles();ps[p.contact.toLowerCase()]=p;localStorage.setItem("forwardProfilesV27",JSON.stringify(ps));localStorage.setItem("forwardActiveV27",p.contact.toLowerCase());}
function activeProfile(){let c=localStorage.getItem("forwardActiveV27");return c?profiles()[c]:null;}
function setProfile(p){profileName.textContent=(p.first+" "+p.surname).trim();pProvince.textContent=p.province;pIndustry.textContent=p.industry;pAge.textContent=p.age;avatar.textContent=(p.first||"F")[0].toUpperCase();status.textContent=`${p.province} • ${p.industry}`;thoughtDisplay.textContent=`“${p.thought||"Can’t wait for Opportunities."}”`;}
function enter(p,delay=true){auth.classList.add("hidden"); if(delay) loading.classList.remove("hidden"); setTimeout(()=>{loading.classList.add("hidden");app.classList.remove("hidden");setProfile(p);renderAll();},delay?5000:0);}
joinBtn.onclick=()=>{if(!firstName.value||!surname.value||!contact.value||!province.value||!age.value||!industry.value){alert("Please complete all fields.");return}if(!consent.checked){alert("Please accept the consent form.");return}let p={first:firstName.value,surname:surname.value,contact:contact.value,province:province.value,age:age.value,industry:industry.value,thought:"Can’t wait for Opportunities."};saveProfile(p);enter(p,true);}
signinBtn.onclick=()=>{let c=signinContact.value.toLowerCase().trim();let p=profiles()[c];if(!p){alert("No Forward profile found. Create an account first.");return}localStorage.setItem("forwardActiveV27",c);enter(p,true);}
signOut.onclick=()=>{localStorage.removeItem("forwardActiveV27");location.reload();}
load();let p=activeProfile();if(p)enter(p,false);

function renderAll(){renderStories();renderFeed();renderRooms();renderEvents();renderMarket();renderReels();renderSocials();applyAdmin();}
function showPage(id){$$(".page").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");$$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===id));}
$$(".nav").forEach(n=>n.onclick=()=>showPage(n.dataset.page));
adminToggle.onclick=()=>{admin=!admin;adminToggle.textContent=admin?"Admin On":"Admin";renderAll();}

function renderStories(){stories.innerHTML; document.getElementById("stories").innerHTML=stories.map((s,i)=>{let label=typeof s==="string"?s:s.label, media=typeof s==="object"?s.media:null;let style=media?`style="background-image:url('${media.url}')"`:"";return `<div class="story ${i==0?"active":""}" data-story="${i}"><div class="ring" ${style}>${media?"":label[0]}</div><small>${label}</small></div>`}).join("");$$(".story").forEach(el=>el.onclick=()=>alert((typeof stories[el.dataset.story]==="string"?stories[el.dataset.story]:stories[el.dataset.story].label)+" story opened"));}
addStoryBtn.onclick=()=>{let label=prompt("Story label","New Story");if(!label)return;let input=fileInput;input.onchange=async()=>{stories.push({label,media:await fileURL(input.files[0])});input.value="";save();renderStories();};input.click();}
quickStory.onclick=()=>addStoryBtn.click();

function mediaHTML(m){if(!m)return ""; if(m.type&&m.type.startsWith("image"))return `<div class="media"><img src="${m.url}"></div>`; if(m.type&&m.type.startsWith("video"))return `<div class="media"><video src="${m.url}" controls playsinline></video></div>`; return `<span class="file-name">${m.name}</span>`}
postPickFile.onclick=()=>{fileInput.onchange=async()=>{pendingPostFile=await fileURL(fileInput.files[0]);postFileName.textContent=pendingPostFile.name;postFileName.classList.remove("hidden");fileInput.value="";};fileInput.click();}
createPost.onclick=()=>{posts.unshift({title:postTitle.value||"Forward Update",type:"Admin Post",body:postBody.value||"New access update.",likes:0,liked:false,media:pendingPostFile});pendingPostFile=null;postFileName.classList.add("hidden");postTitle.value="";postBody.value="";save();renderFeed();}
function renderFeed(){feed.innerHTML=posts.map((p,i)=>`<article class="feed-card"><div class="feed-head"><span>Forward</span><small>${p.type}</small></div><h3>${p.title}</h3><p>${p.body}</p>${mediaHTML(p.media)}<div class="actions"><button class="like ${p.liked?"liked":""}" data-i="${i}">${p.liked?"♥":"♡"} <span>${p.likes}</span></button><button>Comment</button><button>Share</button><button>React</button></div>${admin?`<div class="admin-panel"><button onclick="editPost(${i})">Edit Post</button><button onclick="addPostMedia(${i})">Add Media</button><button class="danger" onclick="delPost(${i})">Delete</button></div>`:""}</article>`).join("");$$(".like").forEach(b=>b.onclick=()=>{let p=posts[b.dataset.i];p.liked=!p.liked;p.likes+=p.liked?1:-1;save();renderFeed();});}
window.editPost=i=>{posts[i].title=prompt("Title",posts[i].title)||posts[i].title;posts[i].body=prompt("Body",posts[i].body)||posts[i].body;save();renderFeed();}
window.addPostMedia=i=>{fileInput.onchange=async()=>{posts[i].media=await fileURL(fileInput.files[0]);fileInput.value="";save();renderFeed();};fileInput.click();}
window.delPost=i=>{posts.splice(i,1);save();renderFeed();}

function rStatus(r){return r.readOnly?"Read-only":r.locked?"Closed":"Open"}
showRoomCreate.onclick=()=>roomCreate.classList.toggle("hidden");
createRoom.onclick=()=>{rooms.unshift({name:roomNameInput.value||"New Room",desc:roomDescInput.value||"Access room",members:0,locked:false,readOnly:false});save();renderRooms();}
function renderRooms(){roomList.innerHTML=rooms.map((r,i)=>`<button class="room-card" data-i="${i}"><div><h3>${r.name}</h3><p>${r.desc}</p></div><div class="room-meta"><span class="status ${rStatus(r)!="Open"?"closed":""}">${rStatus(r)}</span><span class="count">${r.members} Members</span></div></button>`).join("");$$(".room-card").forEach(c=>c.onclick=()=>{activeRoom=+c.dataset.i;openRoom();});}
function openRoom(){let r=rooms[activeRoom];roomTitle.textContent=r.name;roomMeta.textContent=`${rStatus(r)} room • ${r.members} members • reactions enabled`;editRoomName.value=r.name;editRoomDesc.value=r.desc;composer.classList.toggle("hidden",(r.locked||r.readOnly)&&!admin);showPage("roomView");renderMessages();applyAdmin();}
backRooms.onclick=()=>showPage("rooms");saveRoom.onclick=()=>{rooms[activeRoom].name=editRoomName.value;rooms[activeRoom].desc=editRoomDesc.value;save();openRoom();renderRooms();};lockRoom.onclick=()=>{rooms[activeRoom].locked=!rooms[activeRoom].locked;save();openRoom();};readOnlyRoom.onclick=()=>{rooms[activeRoom].readOnly=!rooms[activeRoom].readOnly;save();openRoom();};deleteRoom.onclick=()=>{rooms.splice(activeRoom,1);activeRoom=0;save();showPage("rooms");renderRooms();}
roomPickFile.onclick=()=>{fileInput.onchange=async()=>{let f=await fileURL(fileInput.files[0]);let div=document.createElement("div");div.className="msg";div.innerHTML=`<small>Admin</small>${mediaHTML(f)}${reacts()}`;messages.appendChild(div);attachReacts();fileInput.value="";};fileInput.click();}
function reacts(){return `<div class="reactions">${["❤️","👍","😊","✅","💯"].map(x=>`<button>${x}</button>`).join("")}</div>`}
function attachReacts(){$$(".reactions button").forEach(b=>b.onclick=()=>b.classList.toggle("active"));}
function renderMessages(){messages.innerHTML=`<div class="msg"><small>Forward</small>Welcome To Forward Access.${reacts()}</div><div class="msg"><small>Forward</small>Use this room for signal, movement and opportunity. No noise.${reacts()}</div>`;attachReacts();}
sendMessage.onclick=()=>{if(!messageInput.value.trim())return;let d=document.createElement("div");d.className="msg";d.innerHTML=`<small>You</small>${messageInput.value}${reacts()}`;messages.appendChild(d);messageInput.value="";attachReacts();}

addReelBtn.onclick=()=>{let title=prompt("Reel title","New Reel");if(!title)return;let caption=prompt("Caption","Forward movement.");fileInput.onchange=async()=>{reels.unshift({title,caption,media:await fileURL(fileInput.files[0])});fileInput.value="";save();renderReels();};fileInput.click();}
function renderReels(){reelStack.innerHTML=reels.map((r,i)=>`<div class="reel">${r.media?mediaHTML(r.media):""}<div><h2>${r.title}</h2><p>${r.caption}</p><div>❤️ 👍 😊 ✅ 💯</div>${admin?`<button class="read-more" onclick="editReel(${i})">Edit</button><button class="read-more danger" onclick="delReel(${i})">Delete</button>`:""}</div></div>`).join("");}
window.editReel=i=>{reels[i].title=prompt("Title",reels[i].title)||reels[i].title;reels[i].caption=prompt("Caption",reels[i].caption)||reels[i].caption;save();renderReels();}
window.delReel=i=>{reels.splice(i,1);save();renderReels();}

showEventCreate.onclick=()=>eventCreate.classList.toggle("hidden");eventPickPoster.onclick=()=>{fileInput.onchange=async()=>{pendingEventFile=await fileURL(fileInput.files[0]);eventPosterName.textContent=pendingEventFile.name;eventPosterName.classList.remove("hidden");fileInput.value="";};fileInput.click();}
createEvent.onclick=()=>{events.unshift({title:eventTitleInput.value||"New Event",date:eventDateInput.value||"Coming Soon",price:eventPriceInput.value||"Free",poster:eventTitleInput.value||"Event Poster",details:eventDescInput.value||"Event details.",media:pendingEventFile});pendingEventFile=null;eventPosterName.classList.add("hidden");save();renderEvents();}
function renderEvents(){eventsList.innerHTML=events.map((e,i)=>`<div class="event-card"><div class="event-poster" ${e.media?`style="background-image:url('${e.media.url}')"`:""}>${e.media?"":e.poster}</div><h3>${e.title}</h3><p>${e.date} • ${e.price}</p><button class="read-more" data-i="${i}">See More Details</button><div class="details" id="event${i}"><p>${e.details}</p><button>Register Interest</button>${admin?`<div class="admin-panel"><button onclick="editEvent(${i})">Edit</button><button onclick="eventPoster(${i})">Add / Change Poster</button><button class="danger" onclick="delEvent(${i})">Delete</button></div>`:""}</div></div>`).join("");$$("[data-i].read-more").forEach(b=>b.onclick=()=>$("#event"+b.dataset.i).classList.toggle("open"));}
window.editEvent=i=>{events[i].title=prompt("Title",events[i].title)||events[i].title;events[i].date=prompt("Date",events[i].date)||events[i].date;events[i].price=prompt("Price",events[i].price)||events[i].price;events[i].details=prompt("Details",events[i].details)||events[i].details;save();renderEvents();}
window.eventPoster=i=>{fileInput.onchange=async()=>{events[i].media=await fileURL(fileInput.files[0]);fileInput.value="";save();renderEvents();};fileInput.click();}
window.delEvent=i=>{events.splice(i,1);save();renderEvents();}

showOfferCreate.onclick=()=>offerCreate.classList.toggle("hidden");offerPickImage.onclick=()=>{fileInput.onchange=async()=>{pendingOfferFile=await fileURL(fileInput.files[0]);offerImageName.textContent=pendingOfferFile.name;offerImageName.classList.remove("hidden");fileInput.value="";};fileInput.click();}
createOffer.onclick=()=>{offers.unshift({title:offerTitleInput.value||"New Offer",price:offerPriceInput.value||"Custom",button:offerButtonInput.value,details:offerDescInput.value||"Offer details.",media:pendingOfferFile});pendingOfferFile=null;offerImageName.classList.add("hidden");save();renderMarket();}
function renderMarket(){marketList.innerHTML=offers.map((o,i)=>`<div class="market-card"><div class="product-image" ${o.media?`style="background-image:url('${o.media.url}')"`:""}>${o.media?"":o.title.split(" ")[0]}</div><h3>${o.title}</h3><p>${o.price}</p><button>${o.button}</button><button class="read-more" data-o="${i}">Read More</button><div class="details" id="offer${i}"><p>${o.details}</p>${admin?`<div class="admin-panel"><button onclick="editOffer(${i})">Edit</button><button onclick="offerImage(${i})">Add / Change Image</button><button class="danger" onclick="delOffer(${i})">Delete</button></div>`:""}</div></div>`).join("");$$("[data-o].read-more").forEach(b=>b.onclick=()=>$("#offer"+b.dataset.o).classList.toggle("open"));}
window.editOffer=i=>{offers[i].title=prompt("Title",offers[i].title)||offers[i].title;offers[i].price=prompt("Price",offers[i].price)||offers[i].price;offers[i].button=prompt("Button",offers[i].button)||offers[i].button;offers[i].details=prompt("Details",offers[i].details)||offers[i].details;save();renderMarket();}
window.offerImage=i=>{fileInput.onchange=async()=>{offers[i].media=await fileURL(fileInput.files[0]);fileInput.value="";save();renderMarket();};fileInput.click();}
window.delOffer=i=>{offers.splice(i,1);save();renderMarket();}

saveThought.onclick=()=>{let p=activeProfile();p.thought=thoughtInput.value||p.thought;saveProfile(p);setProfile(p);thoughtInput.value="";}
askAI.onclick=()=>{let q=aiQuestion.value.toLowerCase();let a="Forward connects people and businesses to rooms, opportunities, visibility, funding, partnerships, events and economic movement.";if(q.includes("room"))a="Rooms are private access spaces. Some are open, closed or read-only. Even closed rooms allow reactions.";else if(q.includes("market"))a="Marketplace shows memberships, tickets, partner offers, courses, sponsored products and opportunities.";else if(q.includes("event"))a="Events are Forward access rooms in real life: summits, gatherings, partner sessions and opportunity rooms.";else if(q.includes("earn"))a="Forward Earnings is coming soon for referrals, campaigns, opportunity sharing and partner activity.";aiAnswer.textContent=a;}
function renderSocials(){let items=[["Website",socials.website],["Instagram",socials.instagram],["Facebook",socials.facebook],["LinkedIn",socials.linkedin],["YouTube",socials.youtube]];socialLinks.innerHTML=items.map(x=>x[1]?`<a href="${x[1]}" target="_blank">${x[0]}</a>`:`<button>${x[0]}</button>`).join("");websiteLink.value=socials.website||"";instagramLink.value=socials.instagram||"";facebookLink.value=socials.facebook||"";linkedinLink.value=socials.linkedin||"";youtubeLink.value=socials.youtube||"";}
saveSocials.onclick=()=>{socials={website:websiteLink.value,instagram:instagramLink.value,facebook:facebookLink.value,linkedin:linkedinLink.value,youtube:youtubeLink.value};save();renderSocials();}
$$("[data-admin-go]").forEach(b=>b.onclick=()=>showPage(b.dataset.adminGo));assignAdmin.onclick=()=>alert("Admin saved for visual prototype. Production assignment needs database accounts.");assignPartner.onclick=()=>alert("Partner saved for visual prototype. Production assignment needs database accounts.");
function applyAdmin(){$$(".admin-only").forEach(e=>e.classList.toggle("hidden",!admin));roomAdmin.classList.toggle("hidden",!admin);}
